version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - method: pip
      packages:
        - sphinx
        - sphinx-napoleon
        - pydata-sphinx-theme
