% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Apr-2025 12:28:58
%  MATLAB version: 24.2.0.2773142 (R2024b) Update 2
% -------------------------------------------------------------------
                                                  

atlas = ['C:\Users\brand\OneDrive\Desktop\CMEPDA\progetto esame\data\lp' ...
         'ba40.spm5.avg152T1.gm.label.nii.gz'];
atlas = convertCharsToStrings(atlas);

csv_output = 'risultati.csv';
csv_output = convertCharsToStrings(csv_output);

csv_prefix = 'results';
csv_prefix = convertCharsToStrings(csv_prefix);

folder = ['C:\Users\brand\OneDrive\Desktop\CMEPDA\progetto esame\data\A' ...
          'D_s3\AD_s3'];
folder = convertCharsToStrings(folder);

labels = ['C:\Users\brand\OneDrive\Desktop\CMEPDA\progetto esame\data\l' ...
          'pba40_labelID.txt'];
labels = convertCharsToStrings(labels);

